# Generated by Django 4.2.7 on 2023-11-09 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="expenses.currency",
            ),
        ),
    ]
